name: Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "[${{github.event.pull_request.head.repo.full_name}}]"
